# -*- coding: utf-8 -*-
"""Logic Building Task – 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vEOa5-62vhCAxCogVZiDO2Z_NBA_ngqW

1.User Login Check
# New Section
"""

# Given credentials
correct_username = "admin"
correct_password = "1234"

# Input from user
username = input("Enter username: ")
password = input("Enter password: ")

# Checking login credentials
if username == correct_username and password == correct_password:
    print("Login Successful")
else:
    print("Invalid Credentials")

"""2.Pass / Fail Analyzer"""

marks = [45, 78, 90, 33, 60]

pass_count = 0
fail_count = 0

# Analyze each student's marks
for mark in marks:
    if mark >= 50:
        pass_count += 1
    else:
        fail_count += 1

# Display results
print("Total Students:", len(marks))
print("Passed Students:", pass_count)
print("Failed Students:", fail_count)

"""3.Simple Data Cleaner"""

names = [" Alice ", "bob", " CHARLIE "]

cleaned_names = []

# Clean each name
for name in names:
    clean_name = name.strip().lower()
    cleaned_names.append(clean_name)

# Print cleaned list
print("Cleaned Names:", cleaned_names)

"""4.Message Length Analyzer

"""

messages = ["Hi", "Welcome to the platform", "OK"]

for message in messages:
    length = len(message)
    print(f"Message: '{message}' | Length: {length}")

    if length > 10:
        print("⚠️ This message is longer than 10 characters.")

"""5.Error Message Detector"""

logs = ["INFO", "ERROR", "WARNING", "ERROR"]

error_count = 0

# Count ERROR entries
for log in logs:
    if log == "ERROR":
        error_count += 1

print("Total ERROR messages:", error_count)